/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bill {
  'id' : bigint,
  'dueDate' : string,
  'billingPeriod' : string,
  'tenantId' : bigint,
  'billType' : string,
  'notes' : string,
  'paymentDate' : string,
  'amountDue' : bigint,
  'paidStatus' : boolean,
}
export interface DashboardStats {
  'totalExpectedRentThisMonth' : bigint,
  'totalTenants' : bigint,
  'overdueBills' : bigint,
  'overdueRents' : bigint,
}
export interface PropertyListing {
  'id' : bigint,
  'title' : string,
  'photoUrls' : Array<string>,
  'rentPrice' : bigint,
  'ownerId' : Principal,
  'bedrooms' : bigint,
  'createdAt' : string,
  'isAvailable' : boolean,
  'description' : string,
  'amenities' : Array<string>,
  'address' : string,
  'bathrooms' : bigint,
}
export interface Reminder {
  'status' : string,
  'createdDate' : string,
  'tenantId' : bigint,
  'billType' : string,
  'message' : string,
}
export interface RentPayment {
  'month' : bigint,
  'rentAmount' : bigint,
  'year' : bigint,
  'tenantId' : bigint,
  'amountPaid' : bigint,
  'dueDay' : bigint,
  'notes' : string,
  'paymentDate' : string,
  'paidStatus' : boolean,
}
export interface RentalAgreement {
  'endDate' : string,
  'tenantId' : bigint,
  'startDate' : string,
}
export interface SecurityDeposit {
  'tenantId' : bigint,
  'dateReceived' : string,
  'amount' : bigint,
  'paidStatus' : boolean,
}
export interface Tenant {
  'id' : bigint,
  'leavingDate' : string,
  'name' : string,
  'email' : string,
  'notes' : string,
  'unitNumber' : string,
  'phone' : string,
  'moveInDate' : string,
  'brokerContact' : string,
  'brokerName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBill' : ActorMethod<
    [bigint, string, string, bigint, string, string],
    bigint
  >,
  'addReminder' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  'addRentPayment' : ActorMethod<
    [bigint, bigint, bigint, bigint, bigint, bigint],
    undefined
  >,
  'addRentalAgreement' : ActorMethod<[bigint, string, string], undefined>,
  'addSecurityDeposit' : ActorMethod<
    [bigint, bigint, boolean, string],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createPropertyListing' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      Array<string>,
      string,
    ],
    bigint
  >,
  'createTenant' : ActorMethod<
    [string, string, string, string, string, string, string, string, string],
    bigint
  >,
  'deletePropertyListing' : ActorMethod<[bigint], undefined>,
  'deleteTenant' : ActorMethod<[bigint], undefined>,
  'getAllBills' : ActorMethod<[], Array<Bill>>,
  'getAllPropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getAllTenants' : ActorMethod<[], Array<Tenant>>,
  'getBill' : ActorMethod<[bigint], [] | [Bill]>,
  'getBillsByTenant' : ActorMethod<[bigint], Array<Bill>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyPropertyListings' : ActorMethod<[], Array<PropertyListing>>,
  'getPropertyListing' : ActorMethod<[bigint], PropertyListing>,
  'getReminders' : ActorMethod<[bigint], Array<Reminder>>,
  'getRentPayments' : ActorMethod<[bigint], Array<RentPayment>>,
  'getRentalAgreement' : ActorMethod<[bigint], [] | [RentalAgreement]>,
  'getSecurityDeposit' : ActorMethod<[bigint], [] | [SecurityDeposit]>,
  'getTenant' : ActorMethod<[bigint], Tenant>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateBillStatus' : ActorMethod<
    [bigint, boolean, string, string],
    undefined
  >,
  'updatePropertyListing' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      boolean,
      Array<string>,
    ],
    undefined
  >,
  'updateRentPaymentStatus' : ActorMethod<
    [bigint, bigint, bigint, boolean, string, string],
    undefined
  >,
  'updateTenant' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];