/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Bill = IDL.Record({
  'id' : IDL.Nat,
  'dueDate' : IDL.Text,
  'billingPeriod' : IDL.Text,
  'tenantId' : IDL.Nat,
  'billType' : IDL.Text,
  'notes' : IDL.Text,
  'paymentDate' : IDL.Text,
  'amountDue' : IDL.Nat,
  'paidStatus' : IDL.Bool,
});
export const PropertyListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'photoUrls' : IDL.Vec(IDL.Text),
  'rentPrice' : IDL.Nat,
  'ownerId' : IDL.Principal,
  'bedrooms' : IDL.Nat,
  'createdAt' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'bathrooms' : IDL.Nat,
});
export const Tenant = IDL.Record({
  'id' : IDL.Nat,
  'leavingDate' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'notes' : IDL.Text,
  'unitNumber' : IDL.Text,
  'phone' : IDL.Text,
  'moveInDate' : IDL.Text,
  'brokerContact' : IDL.Text,
  'brokerName' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardStats = IDL.Record({
  'totalExpectedRentThisMonth' : IDL.Nat,
  'totalTenants' : IDL.Nat,
  'overdueBills' : IDL.Nat,
  'overdueRents' : IDL.Nat,
});
export const Reminder = IDL.Record({
  'status' : IDL.Text,
  'createdDate' : IDL.Text,
  'tenantId' : IDL.Nat,
  'billType' : IDL.Text,
  'message' : IDL.Text,
});
export const RentPayment = IDL.Record({
  'month' : IDL.Nat,
  'rentAmount' : IDL.Nat,
  'year' : IDL.Nat,
  'tenantId' : IDL.Nat,
  'amountPaid' : IDL.Nat,
  'dueDay' : IDL.Nat,
  'notes' : IDL.Text,
  'paymentDate' : IDL.Text,
  'paidStatus' : IDL.Bool,
});
export const RentalAgreement = IDL.Record({
  'endDate' : IDL.Text,
  'tenantId' : IDL.Nat,
  'startDate' : IDL.Text,
});
export const SecurityDeposit = IDL.Record({
  'tenantId' : IDL.Nat,
  'dateReceived' : IDL.Text,
  'amount' : IDL.Nat,
  'paidStatus' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBill' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addReminder' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'addRentPayment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      [],
      [],
    ),
  'addRentalAgreement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'addSecurityDeposit' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPropertyListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'createTenant' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deletePropertyListing' : IDL.Func([IDL.Nat], [], []),
  'deleteTenant' : IDL.Func([IDL.Nat], [], []),
  'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
  'getAllPropertyListings' : IDL.Func(
      [],
      [IDL.Vec(PropertyListing)],
      ['query'],
    ),
  'getAllTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
  'getBill' : IDL.Func([IDL.Nat], [IDL.Opt(Bill)], ['query']),
  'getBillsByTenant' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyPropertyListings' : IDL.Func([], [IDL.Vec(PropertyListing)], ['query']),
  'getPropertyListing' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
  'getReminders' : IDL.Func([IDL.Nat], [IDL.Vec(Reminder)], ['query']),
  'getRentPayments' : IDL.Func([IDL.Nat], [IDL.Vec(RentPayment)], ['query']),
  'getRentalAgreement' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(RentalAgreement)],
      ['query'],
    ),
  'getSecurityDeposit' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(SecurityDeposit)],
      ['query'],
    ),
  'getTenant' : IDL.Func([IDL.Nat], [Tenant], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBillStatus' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updatePropertyListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Bool,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateRentPaymentStatus' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateTenant' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Bill = IDL.Record({
    'id' : IDL.Nat,
    'dueDate' : IDL.Text,
    'billingPeriod' : IDL.Text,
    'tenantId' : IDL.Nat,
    'billType' : IDL.Text,
    'notes' : IDL.Text,
    'paymentDate' : IDL.Text,
    'amountDue' : IDL.Nat,
    'paidStatus' : IDL.Bool,
  });
  const PropertyListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'photoUrls' : IDL.Vec(IDL.Text),
    'rentPrice' : IDL.Nat,
    'ownerId' : IDL.Principal,
    'bedrooms' : IDL.Nat,
    'createdAt' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'bathrooms' : IDL.Nat,
  });
  const Tenant = IDL.Record({
    'id' : IDL.Nat,
    'leavingDate' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'notes' : IDL.Text,
    'unitNumber' : IDL.Text,
    'phone' : IDL.Text,
    'moveInDate' : IDL.Text,
    'brokerContact' : IDL.Text,
    'brokerName' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardStats = IDL.Record({
    'totalExpectedRentThisMonth' : IDL.Nat,
    'totalTenants' : IDL.Nat,
    'overdueBills' : IDL.Nat,
    'overdueRents' : IDL.Nat,
  });
  const Reminder = IDL.Record({
    'status' : IDL.Text,
    'createdDate' : IDL.Text,
    'tenantId' : IDL.Nat,
    'billType' : IDL.Text,
    'message' : IDL.Text,
  });
  const RentPayment = IDL.Record({
    'month' : IDL.Nat,
    'rentAmount' : IDL.Nat,
    'year' : IDL.Nat,
    'tenantId' : IDL.Nat,
    'amountPaid' : IDL.Nat,
    'dueDay' : IDL.Nat,
    'notes' : IDL.Text,
    'paymentDate' : IDL.Text,
    'paidStatus' : IDL.Bool,
  });
  const RentalAgreement = IDL.Record({
    'endDate' : IDL.Text,
    'tenantId' : IDL.Nat,
    'startDate' : IDL.Text,
  });
  const SecurityDeposit = IDL.Record({
    'tenantId' : IDL.Nat,
    'dateReceived' : IDL.Text,
    'amount' : IDL.Nat,
    'paidStatus' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBill' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addReminder' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'addRentPayment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        [],
        [],
      ),
    'addRentalAgreement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'addSecurityDeposit' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPropertyListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'createTenant' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deletePropertyListing' : IDL.Func([IDL.Nat], [], []),
    'deleteTenant' : IDL.Func([IDL.Nat], [], []),
    'getAllBills' : IDL.Func([], [IDL.Vec(Bill)], ['query']),
    'getAllPropertyListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getAllTenants' : IDL.Func([], [IDL.Vec(Tenant)], ['query']),
    'getBill' : IDL.Func([IDL.Nat], [IDL.Opt(Bill)], ['query']),
    'getBillsByTenant' : IDL.Func([IDL.Nat], [IDL.Vec(Bill)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyPropertyListings' : IDL.Func(
        [],
        [IDL.Vec(PropertyListing)],
        ['query'],
      ),
    'getPropertyListing' : IDL.Func([IDL.Nat], [PropertyListing], ['query']),
    'getReminders' : IDL.Func([IDL.Nat], [IDL.Vec(Reminder)], ['query']),
    'getRentPayments' : IDL.Func([IDL.Nat], [IDL.Vec(RentPayment)], ['query']),
    'getRentalAgreement' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(RentalAgreement)],
        ['query'],
      ),
    'getSecurityDeposit' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(SecurityDeposit)],
        ['query'],
      ),
    'getTenant' : IDL.Func([IDL.Nat], [Tenant], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBillStatus' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updatePropertyListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Bool,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateRentPaymentStatus' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Bool, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateTenant' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };